version: "3.9"
services:
  python-telegram-bot:
    build:
      context: .
      dockerfile: ptb.Dockerfile
      args:
        IMAGE_TAG: latest
    image: python-telegram-bot:latest
    volumes:
      - ./logs:/logs
  python-telegram-bot-tests:
    build:
      context: .
      dockerfile: ptbtest.Dockerfile
    image: python-telegram-bot-tests:latest
    volumes:
      - ./logs:/logs
    depends_on:
      - python-telegram-bot
volumes:
  logs: