pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'building...'
                sh 'DOCKER_TLS_VERIFY=0 docker compose -f devops/docker-compose.yml build python-telegram-bot'
            }
        }
        post {
            always{
            }
            success {
                echo '   success'
            }
            failure {
                echo '   failure'
            }
        }
    }
}